### PR TITLE
add when, unless

### PR DESCRIPTION
**Pull request by Heather**
Just playing around with code to get more about how it works actually =)

### CODE REVIEW

**Comment by lolisa** [comment]
Good job :smile: 
I also spotted the problem of declaring adt first and declaring constructors next, and I think it is sort of putting the cart before the horse... So I'm working on a nicer interface that do all at once, called DECLARE_ADT.
BTW if you have any question/comment feel free to ask, I am more than happy to communicate with you.
P.S. The thought of marisa and alice making cirno together is so ridiculous I am literally loling

**Comment by lolisa** [comment]
Also @Heather the When you just implement always run the exp...

**Comment by Heather** [comment]
@lolisa do you have some IM? using some slack or freenode rooms?

agreed with problem and I was looking into ADT header with scary macros involving some boost magic :D sure I have a lot of questions

exp..?

**Comment by Heather** [comment]
Oh hell it was my mistake

**Comment by Heather** [comment]
https://github.com/lolisa/Cirno/pull/8

**Comment by lolisa** [comment]
Cool, I use freenode, let's get #cirno or something similar
Dont worry about ADT, I can handle it, but if you wanna learn, sure, happy to help :smile: 
I am having a busy university life, plus a strange biological clock, so when you cant find me on freenode you can send me email (lolisa@marisa.moe

**Pull request merged**
